### ISSUE TITLE
v02_01_00 build fails with clang

### ISSUE THREAD

**Issue by tomjunk** [DUNE/duneanaobj#7]
From the Jenkins build with c7.  Looks like a problem the the undeclared identifier _Float16

[ 47%] Building CXX object duneanaobj/duneanaobj/StandardRecord/CMakeFiles/duneanaobj_StandardRecord.dir/SRVector3D.cxx.o
INFO Parsing source file "/scratch/workspace/duneanaobj-release-build/BUILDTYPE/debug/QUAL/c7/label1/swarm/label2/SLF7/temp/srcs/duneanaobj/duneanaobj/StandardRecord/StandardRecord.h" ... 
INFO Parsing source file "/scratch/workspace/duneanaobj-release-build/BUILDTYPE/debug/QUAL/c7/label1/swarm/label2/SLF7/temp/srcs/duneanaobj/duneanaobj/StandardRecord/StandardRecord.h" ... 
In file included from /scratch/workspace/duneanaobj-release-build/BUILDTYPE/debug/QUAL/c7/label1/swarm/label2/SLF7/temp/srcs/duneanaobj/duneanaobj/StandardRecord/StandardRecord.hIn file included from :12/scratch/workspace/duneanaobj-release-build/BUILDTYPE/debug/QUAL/c7/label1/swarm/label2/SLF7/temp/srcs/duneanaobj/duneanaobj/StandardRecord/StandardRecord.h:
:In file included from 12/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/vector:
:In file included from 270/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/vector:
:In file included from 270/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/__bit_reference:
:In file included from 15/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/__bit_reference:
:In file included from 15/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/algorithm:
:In file included from 640/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/algorithm:
:In file included from 640/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/initializer_list:
:In file included from 47/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/initializer_list:
:In file included from 47/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/cstddef:
:In file included from 110/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/cstddef:
:110:
/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/type_traits:/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/type_traits740::74056::56 :error : erroruse of undeclared identifier '_Float16': 
use of undeclared identifier '_Float16'
template <>          struct __libcpp_is_floating_point<_Float16>    : public true_type {};template <>          struct __libcpp_is_floating_point<_Float16>    : public true_type {};

                                                       ^                                                       ^

1 error generated.
Traceback (most recent call last):
  File "/cvmfs/dune.opensciencegrid.org/products/dune/srproxy/v00.36//bin/gen_srproxy", line 499, in <module>
    main()
  File "/cvmfs/dune.opensciencegrid.org/products/dune/srproxy/v00.36//bin/gen_srproxy", line 453, in main
    decls = pygccxml.parser.parse([input_header], config)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/__init__.py", line 51, in parse
1 error generated.
Traceback (most recent call last):
  File "/cvmfs/dune.opensciencegrid.org/products/dune/srproxy/v00.36//bin/gen_srproxy", line 499, in <module>
    main()
  File "/cvmfs/dune.opensciencegrid.org/products/dune/srproxy/v00.36//bin/gen_srproxy", line 453, in main
    decls = pygccxml.parser.parse([input_header], config)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/__init__.py", line 51, in parse
    declarations = parser.read_files(files, compilation_mode)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/project_reader.py", line 264, in read_files
    declarations = parser.read_files(files, compilation_mode)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/project_reader.py", line 264, in read_files
    return self.__parse_file_by_file(files)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/project_reader.py", line 292, in __parse_file_by_file
    return self.__parse_file_by_file(files)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/project_reader.py", line 292, in __parse_file_by_file
    decls = reader.read_file(header)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/source_reader.py", line 299, in read_file
    decls = reader.read_file(header)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/source_reader.py", line 299, in read_file
[ 52%] Linking CXX shared library ../../slf7.x86_64.c7.debug/lib/libduneanaobj_StandardRecord.so
    return self.read_cpp_source_file(source_file)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/source_reader.py", line 318, in read_cpp_source_file
    return self.read_cpp_source_file(source_file)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/source_reader.py", line 318, in read_cpp_source_file
    xml_file = self.create_xml_file(ffname)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/source_reader.py", line 264, in create_xml_file
    raise RuntimeError(
RuntimeError: Error occurred while running CASTXML:  status:1
    xml_file = self.create_xml_file(ffname)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0c/lib/python3.9/site-packages/pygccxml/parser/source_reader.py", line 264, in create_xml_file
    raise RuntimeError(
RuntimeError: Error occurred while running CASTXML:  status:1
gmake[2]: *** [duneanaobj/duneanaobj/StandardRecord/Proxy/SRProxy.cxx] Error 1
gmake[1]: *** [duneanaobj/duneanaobj/StandardRecord/Proxy/CMakeFiles/duneanaobj_StandardRecordProxy.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: *** [duneanaobj/duneanaobj/StandardRecord/Flat/FlatRecord.cxx] Error 1
gmake[1]: *** [duneanaobj/duneanaobj/StandardRecord/Flat/CMakeFiles/duneanaobj_StandardRecordFlat.dir/all] Error 2
[ 52%] Built target duneanaobj_StandardRecord
gmake: *** [all] Error 2

**Comment by cjbackhouse** [comment]
Should be fixed by https://github.com/DUNE/duneanaobj/commit/ba165f0b71205dc5955b3aec8c2035a07c17d417
I don't think there's any need to respin the current release, but we can pick it up for v02.02

**Comment by tomjunk** [comment]
Looks good.  I tried both clang and gcc builds interactively and they both succeeded.
